config/routes.rb
Rails.application.routes.draw do
  
  root "home#index"

  get 'contact_us' => "home#contact_us"
  get 'menu' => "home#menu"

  resources :food_items do
  	resources :orders
  end
  
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food_item.rb
class FoodItem < ApplicationRecord
  belongs_to :section
  validates :name, :price, presence: true
  has_many :orders

  def self.search(search)
  	search = search.downcase
  	where("LOWER(name) ILIKE ? or LOWER(description) LIKE ?", "#{search}%", "%#{search}%")
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :food_item
  validates :quantity, presence: true, numericality: true

end

app/models/section.rb
class Section < ApplicationRecord
	has_many :food_items

	def to_s
		name || "No name is defined"
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/food_items_controller.rb
class FoodItemsController < ApplicationController
  before_action :set_food_item, only: [:show, :edit, :update, :destroy]

  # GET /food_items
  # GET /food_items.json
  def index
    @food_items = FoodItem.all
  end

  # GET /food_items/1
  # GET /food_items/1.json
  def show
  end

  # GET /food_items/new
  def new
    @food_item = FoodItem.new
  end

  # GET /food_items/1/edit
  def edit
  end

  # POST /food_items
  # POST /food_items.json
  def create
    @food_item = FoodItem.new(food_item_params)

    respond_to do |format|
      if @food_item.save
        format.html { redirect_to @food_item, notice: 'Food item was successfully created.' }
        format.json { render :show, status: :created, location: @food_item }
      else
        format.html { render :new }
        format.json { render json: @food_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /food_items/1
  # PATCH/PUT /food_items/1.json
  def update
    respond_to do |format|
      if @food_item.update(food_item_params)
        format.html { redirect_to @food_item, notice: 'Food item was successfully updated.' }
        format.json { render :show, status: :ok, location: @food_item }
      else
        format.html { render :edit }
        format.json { render json: @food_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /food_items/1
  # DELETE /food_items/1.json
  def destroy
    @food_item.destroy
    respond_to do |format|
      format.html { redirect_to food_items_url, notice: 'Food item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food_item
      @food_item = FoodItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_item_params
      params.require(:food_item).permit(:name, :description, :price, :section_id, :image_url)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def contact_us
  end

  def menu
  	@sections = Section.all
    @food_items = FoodItem.all
  	if params[:section_id].present?
  		@current_secion = Section.find(params[:section_id])
      @food_items = @current_secion.food_items
  	end

  	if params[:search] && !params[:search].empty?
    	@food_items = FoodItem.search(params[:search])
    	@search_keyword = params[:search]
  	end

    if params[:sort_column]
      @food_items = FoodItem.order("#{params[:sort_column]} #{params[:sort_direction]}")
    end
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	def new
		@item = FoodItem.find(params[:food_item_id])
		@order = @item.orders.build
	end

	def create 
		@item = FoodItem.find(params[:food_item_id])
		@order = @item.orders.build order_params

		if @order.save!
			flash[:notice] = "Thanks for your order.
			The meal will be shipped to #{@order.address} at #{@order.created_at.strftime('%B %d, %Y')}"
			redirect_to menu_path
		else 
			render 'new'
		end
	end

	def order_params
		params.require(:order).permit(:quantity, :address)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/food_items_helper.rb
module FoodItemsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/food_items/_form.html.erb
<%= form_for(food_item) do |f| %>
  <% if food_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(food_item.errors.count, "error") %> prohibited this food_item from being saved:</h2>

      <ul>
      <% food_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="form-group">
    <%= f.label :section_id %>
    <%= f.select :section_id, Section.all.collect { |e| [e.name, e.id] }, {} , class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :image_url %>
    <%= f.text_field :image_url %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/food_items/details.html.erb
<h1>Details Item</h1>

app/views/food_items/edit.html.erb
<h1>Editing Food Item</h1>

<%= render 'form', food_item: @food_item %>

<%= link_to 'Show', @food_item %> |
<%= link_to 'Back', food_items_path %>

app/views/food_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Food Items</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Section</th>
      <th>Image url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @food_items.each do |food_item| %>
      <tr>
        <td><%= food_item.name %></td>
        <td><%= food_item.description %></td>
        <td><%= food_item.price %></td>
        <td><%= food_item.section %></td>
        <td><%= food_item.image_url %></td>
        <td><%= link_to 'Show', food_item %></td>
        <td><%= link_to 'Edit', edit_food_item_path(food_item) %></td>
        <td><%= link_to 'Destroy', food_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Food Item', new_food_item_path %>

app/views/food_items/new.html.erb
<h1>New Food Item</h1>

<%= render 'form', food_item: @food_item %>

<%= link_to 'Back', food_items_path %>

app/views/food_items/show.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Description</th>
      <th>Image</th>
      <th></th>
    </tr>
  </thead>

<div class='tbody'>
      <tr>

        <td><%= @food_item.description %></td>
        <td><%= image_tag @food_item.image_url, size: '600x600' %></td>
        
      </tr>
      <tr>
      <td><%= link_to 'Back', menu_path %> </td>
        
      </tr>

  </div>
  
  

</table>

app/views/home/contact_us.html.erb
<h1>Contact Us</h1>
<div class="row">
	<div class="col-sm-6">
		<div class="card card-block">
			<address>
			<strong>Ngon Restaurant</strong> <br>
			Addresss: 123 Pham Van Dong
			</address>
		</div>
	</div>
	<div class="col-sm-6">
		<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3919.2297474066604!2d106.66073421488379!3d10.793707861825771!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3175293267b0e37b%3A0xc5442433a9559a7a!2sPham+Van+Hai+Market!5e0!3m2!1sen!2s!4v1487432985354" width="100%" height="100%" frameborder="0" style="border:0" allowfullscreen></iframe>
	</div>
</div>

app/views/home/index.html.erb
<h1>Welcome to Ngon restaurant</h1>

<div class="jumbotron hero">
	
	

	<table>
		<tbody>
			<tr>
				<td><%= link_to "Menu", menu_path, class: 'btn btn-primary' %></td>
				<td><%= link_to "Contact_Us", contact_us_path, class: 'btn btn-primary'  %></td>
				
			</tr>
			<tr>
			<td></td>
				
			</tr>
		</tbody>
	</table>
	<br>
	<%= image_tag "http://vina.com/wp-content/uploads/2015/09/Ngon-Restaurant.jpg", width: "100%" %>

	
</div>

app/views/home/menu.html.erb
<h1>Menu</h1>

<% if  flash[:notice] %>
	<div class="alert alert-success"> <%= flash[:notice] %> </div>
<% end %>

<table width="100%" class="table">
	<tr>
		<td>
			<div class="btn-group" role="group" aria-label="Basic example">
			  <% @sections.each do |section| %>
				<%= link_to section.name, menu_path(section_id: section.id), class: "btn #{params[:section_id]==section.id.to_s ? 'btn-primary active' : 'btn-secondary'}"  %>
					<%end%>
				</div>
		</td>
		<td>
			<div class="container">
				<%= hidden_field_tag :section, params[:section] %>
				<%= form_tag nil, method: 'get' do %>

					<div class="form-inline">
					<div class="row">
						<div class="col">
							<%= select_tag :sort_column, options_for_select(['Name', 'Price']), class: 'form-control'  %>
						</div> 
						<div class="col">
							<%= select_tag :sort_direction, options_for_select(['Asc', 'Desc']), class: 'form-control'  %>
						</div>

						<div class="col">
							<%= submit_tag "Sort", class: 'btn btn-primary' %>

						</div>
					</div>
						
						
						
			</div>
			

		<% end %>
</div>

		</td>

	</tr>

</table>






<table class="table">
	<thead>
		<tr>
			<th>Name</th>
			<th>Image</th>
			<th>Description</th>
			<th>Price</th>
			<th></th>
		</tr>
	</thead>

<div class='tbody'>

<% @food_items.all.each do |item| %>
		
			<tr>
				<td><%= link_to item.name, item %></td>
				<td><%= link_to image_tag(item.image_url, size: "300x300"), item %></td>
				<td><%= truncate item.description, length: 300 %></td>
				<td> <%= number_to_currency item.price %> </td>
				<td><%= link_to "Order", new_food_item_order_path(item), class: 'btn btn-primary' %></td>
			</tr>

	</div>
	
	
<%end%>
</table>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-toggleable-md navbar-light bg-faded style=background-color: #e3f2fd;">

  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="<%= root_path %>"><strong>Ngon Restaurant</strong></a>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="<%= menu_path %>">Menu <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="<%= contact_us_path %>">Contact Us <span class="sr-only">(current)</span></a>
      </li>
    </ul>

        <form class="form-inline my-2 my-lg-0">
      <%= form_tag menu_path, method: 'get' do %>
       <p>
          <div class="">
            <%= text_field_tag :search %>
            <%= submit_tag "Search", class: "btn btn-outline-success my-2 my-sm-0"   %>
          </div>
      </p>
  <% end %>
    </form>
      
        
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ngon</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	
  	<div class="container">
	  	<%=  render 'layouts/navbar' %>
	    <%= yield %>
    </div>
  </body>
</html>

app/views/orders/new.html.erb
<h1>Order for <%= @item.name %></h1>

<%= form_for @order, url: food_item_orders_path(@item) do |f| %>
<% if @order.errors.present? %>
	<div class="alert alert-danger"><%= @order.errors.full_messages.to_sentence%></div>
<% end %>
<div class="form_group">
	<%= f.label :quantity %>
	<%= f.number_field :quantity %><br>
	<%= f.label :address %>
	<%= f.text_field :address %>
</div>
	<%= f.submit nil, class: 'btn btn-primary' %>
<%end%>
<br>

<table class="table table-inverse">
  <thead>
    <tr>
      <th>Description</th>
      <th>Image</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row"><%= @item.description %></th>
      <td><%= image_tag @item.image_url, size: "400x400" %></td>
    </tr>
    </tr>
  </tbody>
</table>